build:
    nodes:
        coverage:
            tests:
                override:
                    - command:
                          - export JWT_SECRET='notSafeSecret'
                          - chmod +x db/reset_db_test.bash
                          - npm test
                      coverage:
                          file: coverage/clover.xml
                          format: clover
