build:
    nodes:
        coverage:
            tests:
                override:
                    - command: chmod +x db/reset_db_test.bash
                    - command: npm test
                        coverage:
                            file: coverage/clover.xml
                            format: clover
